apiVersion: v1
kind: PersistentVolume
metadata:
  name: navya-pv
spec:
  capacity:
    storage: 10Gi  # Must match the size of the GCP disk
  accessModes:
    - ReadWriteOnce  # GCE Persistent Disk supports RWO, not RWX
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: gke-pv-disk  # Must match the GCP disk name
    fsType: ext4
